name: SerialEM_pytorch
channels:
 - conda-forge
 - pytorch
 - nvidia
dependencies:
 - python=3.9
 - pytorch=2.2.0
 - torchvision=0.17.0
 - pytorch-cuda=11.8
 - pip
 - pip:
   - nnunetv2==2.2.1
   - ultralytics==8.1.14
   - mrcfile==1.5.0