name: SerialEM_SPACEtomo
channels:
 - conda-forge
 - pytorch
 - nvidia
dependencies:
 - python=3.9
 - pytorch=2.2.0
 - torchvision=0.17.0
 - pytorch-cuda=11.8
 - mrcfile=1.5.0
 - pip
 - pip:
   - nnunetv2==2.3.1
   - ultralytics==8.1.34
   - dearpygui==1.11.1