name: SerialEM_pytorch
channels:
 - conda-forge
 - pytorch
 - nvidia
dependencies:
 - python=3.9
 - pytorch
 - torchvision
 - pytorch-cuda=11.8
 - pip
 - pip:
   - nnunetv2
   - ultralytics
   - mrcfile